# Generated by Django 5.2.10 on 2026-05-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorías'},
        ),
    ]
